In [1]:
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import RandomForestClassifier

In [2]:
df = pd.read_csv('heart_disease.csv')
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,NaN,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [3]:
def scaled_data(df):
    age,chol,target= np.array(df['age']) ,np.array(df['chol']),np.array(df['target'])
    dataset = np.stack([age,chol,target])
    dataset = dataset.T
    dataset=np.random.permutation(dataset)
    dataset = dataset.T
    n = len(dataset[0])
    pct = int(n*0.8)
    x_train = dataset.T[:][:pct]
    y_train = dataset[2][:pct]
    x_test = dataset.T[:][pct:]
    y_test = dataset[2][pct:]
    x_train=np.delete(x_train.T,2,0)
    x_test=np.delete(x_test.T,2,axis=0)
    return x_train.T,y_train,x_test.T,y_test

In [4]:
x_train,y_train,x_test,y_test= scaled_data(df)

In [5]:
def RandomRegression(x_train,y_train,x_test,y_test):
    Modelreg= RandomForestRegressor(n_estimators = 1000, random_state = 0)
    Modelreg.fit(x_train,y_train)
    pred = Modelreg.predict(x_test)
    return pred

In [6]:
def RandomClassification(x_train,y_train,x_test,y_test):
    Modelclass = RandomForestClassifier(max_depth=2, random_state=0)
    Modelclass.fit(x_train,y_train)
    pred = Modelclass.predict(x_test)
    return pred

In [7]:
pred_reg = RandomRegression(x_train,y_train,x_test,y_test)
pred_class = RandomClassification(x_train,y_train,x_test,y_test)

In [8]:
pred_reg,pred_class

(array([0.692     , 0.32414048, 0.053     , 0.658     , 0.347     ,
        0.486     , 0.459     , 0.7815    , 0.803     , 0.75908333,
        0.469     , 0.677     , 0.34871905, 0.299     , 0.8495    ,
        0.75456429, 0.2       , 0.517     , 0.38293333, 0.603     ,
        0.233     , 0.907     , 0.917     , 0.31066667, 0.606     ,
        0.028     , 0.486     , 0.72883333, 0.493     , 0.91      ,
        0.878     , 0.8       , 0.45213333, 0.06      , 0.47405   ,
        0.223     , 0.89633333, 0.1288    , 0.251     , 0.003     ,
        0.80466667, 0.279     , 0.042     , 0.556     , 0.693     ,
        0.724     , 0.611     , 0.18950238, 0.905     , 0.024     ,
        0.894     , 0.864     , 0.59      , 0.96      , 0.953     ,
        0.35866667, 0.622     , 0.471     , 0.69526667, 0.146     ,
        0.907     ]),
 array([1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1,
        1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
        1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1], dtype=int64))

In [9]:
def accuracy(pred_class,y_test):
    acc = 0
    for i in range(len(y_test)):
        if(pred_class[i]==y_test[i]):
            acc+=1
    return acc/len(y_test)

In [11]:
accuracy(pred_class,y_test)*100

62.295081967213115